server {
    listen 80;
    server_name unbarPDF.com www.unbarpdf.com;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/recto/recto.sock;
    }

    # Allow large PDF uploads (up to 500MB)
    client_max_body_size 500M;

    # Serve static files directly
    location /static/ {
        alias /var/www/recto/static/;
    }
}
